export const monthData = [
  {label: "Toute l'année", value: null},
  {label: 'Janvier', value: 1},
  {label: 'Février', value: 2},
  {label: 'Mars', value: 3},
  {label: 'Avril', value: 4},
  {label: 'Mai', value: 5},
  {label: 'Juin', value: 6},
  {label: 'Juillet', value: 7},
  {label: 'Aout', value: 8},
  {label: 'Septembre', value: 9},
  {label: 'Octobre', value: 10},
  {label: 'Novembre', value: 11},
  {label: 'Décembre', value: 12},
];

export const hourData = [
  {label: 'Toute la journée', value: null},
  {label: '00h', value: 0},
  {label: '01h', value: 1},
  {label: '02h', value: 2},
  {label: '03h', value: 3},
  {label: '04h', value: 4},
  {label: '05h', value: 5},
  {label: '06h', value: 6},
  {label: '07h', value: 7},
  {label: '08h', value: 8},
  {label: '09h', value: 9},
  {label: '10h', value: 10},
  {label: '11h', value: 11},
  {label: '12h', value: 12},
  {label: '13h', value: 13},
  {label: '14h', value: 14},
  {label: '15h', value: 15},
  {label: '16h', value: 16},
  {label: '17h', value: 17},
  {label: '18h', value: 18},
  {label: '19h', value: 19},
  {label: '20h', value: 20},
  {label: '21h', value: 21},
  {label: '22h', value: 22},
  {label: '23h', value: 23},
];
